name: Storage
version: '${project.version}'
main: net.danh.storage.Storage
author: VoChiDanh, hongminh54
description: "${project.description}"
api-version: '1.13'
load: STARTUP
provides:
  - StorageAPI
softdepend:
  - WorldGuard
  - PlaceholderAPI
commands:
  storage:
    description: Main command
    aliases:
      - kho
permissions:
  storage.toggle:
    description: Toggle permission
  storage.admin:
    description: Admin permission
  storage.admin.add:
    description: Admin add permission command
  storage.admin.remove:
    description: Admin remove permission command
  storage.admin.set:
    description: Admin set permission command
  storage.admin.max:
    description: Admin max permission command
  storage.admin.reload:
    description: Admin reload permission command
  storage.admin.specialmaterial:
    description: Admin special material permission command
  storage.admin.reset:
    description: Admin reset permission command
  storage.admin.enchant:
    description: Admin enchant permission command
  storage.transfer.use:
    description: Use transfer feature
    default: true
  storage.enchant.use:
    description: Use enchant items
    default: true
  storage.event.admin:
    description: Admin event management permission
  storage.event.view:
    description: View event status permission
    default: true
  storage.transfer.multi:
    description: Use multi transfer feature
    default: true
  storage.transfer.log:
    description: View own transfer logs
    default: true
  storage.transfer.log.others:
    description: View other players transfer logs
    default: true
  storage.transfer.admin:
    description: Bypass transfer cooldown and limitations
    default: op
  storage.convert:
    description: Use convert materials feature
    default: op
  storage.craft.use:
    description: Use custom recipe crafting
    default: true
  storage.craft.admin:
    description: Access recipe editor and management
    default: op
  storage.craft.enhanced:
    description: Craft enhanced tier recipes
    default: true
  storage.craft.magic:
    description: Craft magic tier recipes
    default: true
  storage.craft.ultimate:
    description: Craft ultimate tier recipes
    default: op
